### PR TITLE
docs: Readme Files Update

### PR DESCRIPTION
**Pull request by akhilsunilkumar**

### CODE REVIEW

**Review by ankur4u007 — CHANGES_REQUESTED** [review]
@akhilsunilkumar  Can you please also update https://github.com/lowes/auditor/blob/main/app/README.md with correct details. LGTM otherwise! Thanks!

**Comment by akhilsunilkumar** [comment]
> Hi @ankur4u007, The App module is a standalone Module right, so what Should I update in the README file ?

**Comment by akhilsunilkumar** [comment]
> @akhilsunilkumar Can you please also update https://github.com/lowes/auditor/blob/main/app/README.md with correct details. LGTM otherwise! Thanks!

@ankur4u007 , Updated the PR, Can you please have a look. Thanks !

**Comment by akhilsunilkumar** [comment]
Closes #3 once this PR is merged

**Review by ankur4u007 — APPROVED** [review]
LGTM! Nicely done 🎉 @akhilsunilkumar

**Pull request merged**
